services:
  postgres:
    image: postgres:16
    container_name: diabetes-cdss-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: diabetes_cdss
      POSTGRES_USER: cdss_user
      POSTGRES_PASSWORD: cdss_dev_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: